version: '3.8'

services:
  jellypatrol:
    # Use the pre-built image from GHCR
    image: ghcr.io/d3v1l1989/jellypatrol:latest
    
    # Or build locally (uncomment the lines below and comment the image line above)
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    
    container_name: jellypatrol
    restart: unless-stopped
    
    # Environment variables - copy .env.example to .env and configure
    env_file:
      - .env
    
    # Alternative: specify environment variables directly
    # environment:
    #   - CHECK_INTERVAL_SECONDS=30
    #   - RESOLUTION_POLICY=4K
    #   - KILL_STREAMS=true
    #   - CHECK_AUDIO_TRANSCODES=false
    #   - SERVER1_ENABLED=true
    #   - SERVER1_NAME=My Jellyfin Server
    #   - SERVER1_TYPE=jellyfin
    #   - SERVER1_URL=http://jellyfin:8096
    #   - SERVER1_API_KEY=your_api_key_here
    
    # Network mode for accessing other containers
    # Use 'host' if your media servers are on the host network
    # network_mode: host
    
    # Or connect to specific networks
    networks:
      - mediaserver
    
    # Health check
    healthcheck:
      test: ["CMD", "python3", "-c", "import requests; print('Healthy')"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 30s
    
    # Resource limits (optional)
    deploy:
      resources:
        limits:
          memory: 128M
          cpus: '0.5'
        reservations:
          memory: 64M
          cpus: '0.1'

# Example network configuration
networks:
  mediaserver:
    external: true
    # Or create a new network:
    # driver: bridge